[package]
description = "Simple BIP-39 mnemonic validator: language detection, word count and checksum. No seed derivation."
readme = "README.md"
license = "MIT"
keywords = ["bip39", "mnemonic", "wallet", "crypto", "checksum"]
categories = ["cryptography::cryptocurrencies", "parsing"]
documentation = "https://docs.rs/bip39-check"
# repository = "https://github.com/Eduprogrammer/bip39-check"  # (adicione quando subir pro GitHub)
name = "bip39-check"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

include = [
  "Cargo.toml",
  "README.md",
  "LICENSE",
  "src/**",
  "examples/**",
]

[dependencies]
bip39 = { version = "2.2.0", default-features = false, features = ["std", "spanish", "french", "italian", "portuguese", "japanese", "korean", "chinese-simplified", "chinese-traditional", "czech"] }
unicode-normalization = "0.1.25"



